---
# Must specify the version and download location of the java rpm
# vars:
#   java_version: 7u5
#   java_baseurl: http://somewhere_to_wget_install_file/
## install ruby with rbenv and uninstall system default
- name: install wget
  action: yum pkg=wget state=installed
- name: system java not installed
  action: yum pkg=java state=removed
- name: copy java install script
  action: template src='common/templates/install_java.sh.j2' dest='/usr/local/src/install_java.sh' mode=0755
- name: run install script
  action: shell /usr/local/src/install_java.sh
