---
- name: install mysql
  action: yum name=mysql-server state=installed

- name: copy my.cnf
  action: template src="common/templates/my.cnf.j2" dest="/etc/my.cnf"
- name: start mysql
  action: service name=mysqld state=started enabled=yes

- name: copy monit file
  action: copy src="common/files/mysql.monit.conf" dest="/etc/monit.d/mysql.conf"


- name: restart monit
  action: service name=monit state=restarted
