---
# Must specify the version and download location of the java rpm
# vars:
#   java_version: 7u5
#   java_baseurl: http://somewhere_to_wget_install_file/
## install ruby with rbenv and uninstall system default
- name: remove default java
  action: yum name=java state=removed
  tags:
    - openjdk
- name: install java
  action: yum name=jdk state=installed
  tags:
    - jdk


- name: install java_home in profile
  action: file src=common/files/java.sh dest/etc/profile.d/java.sh
  tags:
    - jdk
